### Create a bootcamp
POST http://localhost:5000/api/v1/bootcamps
Content-Type: application/json

{
    "_id": "5d713a66ec8f2b88b8f830b8",
    "user": "5d7a514b5d2c12c7449be046",
    "name": "ModernTech Bootcamp",
    "description": "ModernTech has one goal, and that is to make you a rockstar developer and/or designer with a six figure salary. We teach both development and UI/UX",
    "website": "https://moderntech.com",
    "phone": "(222) 222-2222",
    "email": "enroll@moderntech.com",
    "address": "220 Pawtucket St, Lowell, MA 01854",
    "careers": ["Web Development", "UI/UX", "Mobile Development"],
    "housing": false,
    "jobAssistance": true,
    "jobGuarantee": false,
    "acceptGi": true
}


### Get Bootcamps
GET http://localhost:5000/api/v1/bootcamps


### Get Single Bootcamp
GET http://localhost:5000/api/v1/bootcamps/6192f39f11beb9cbd574f034
